import type { Metadata } from "next";
import "./globals.css";
import "@/lib/firebase/client";
import { Rubik } from 'next/font/google'
 
const rubik = Rubik({
  subsets: ['cyrillic', 'latin'],
  variable: '--font-rubik',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk-UA">
      <body
        className={`${rubik.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
